<?php

return [
    'name' => 'Lawyer',
    'route_prefix' => '',
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => app_path('Modules/Lawyer/storage'),
            'url' => env('APP_URL').'/modules/lawyer/storage',
            'visibility' => 'public',
        ],
    ],
    'default_disk' => 'lawyer_local',
    'navigation' => [
        'backend-nav' => [
            [
                'item_slug' => 'lawyer-directory-backend-nav',
                'name' => __('Lawyer Directory'),
                'value' => ['name' => 'javascript:;'],
                'class' => '',
                'icon' => 'fa fa-balance-scale',
                'beginning_text' => '',
                'ending_text' => '',
                'type' => 'link',
                'parent_slug' => null,
                'new_tab' => '0',
                'mega_menu' => '0',
                'order' => 2,
            ],
            [
                'item_slug' => 'lawyer-lawyers-backend-nav',
                'name' => __('Lawyers'),
                'value' => ['name' => 'lawyer.admin.lawyers.index'],
                'class' => '',
                'icon' => 'laf laf-user-tie',
                'beginning_text' => '',
                'ending_text' => '',
                'type' => 'route',
                'parent_slug' => 'lawyer-directory-backend-nav',
                'new_tab' => '0',
                'mega_menu' => '0',
            ],
            [
                'item_slug' => 'lawyer-categories-backend-nav',
                'name' => __('Categories'),
                'value' => ['name' => 'lawyer.admin.categories.index'],
                'class' => '',
                'icon' => 'laf laf-list',
                'beginning_text' => '',
                'ending_text' => '',
                'type' => 'route',
                'parent_slug' => 'lawyer-directory-backend-nav',
                'new_tab' => '0',
                'mega_menu' => '0',
            ],
            [
                'item_slug' => 'lawyer-sub-categories-backend-nav',
                'name' => __('Sub-categories'),
                'value' => ['name' => 'lawyer.admin.sub-categories.index'],
                'class' => '',
                'icon' => 'laf laf-list-alt',
                'beginning_text' => '',
                'ending_text' => '',
                'type' => 'route',
                'parent_slug' => 'lawyer-directory-backend-nav',
                'new_tab' => '0',
                'mega_menu' => '0',
            ],
            [
                'item_slug' => 'lawyer-locations-backend-nav',
                'name' => __('Locations'),
                'value' => ['name' => 'lawyer.admin.locations.index'],
                'class' => '',
                'icon' => 'laf laf-map-marker',
                'beginning_text' => '',
                'ending_text' => '',
                'type' => 'route',
                'parent_slug' => 'lawyer-directory-backend-nav',
                'new_tab' => '0',
                'mega_menu' => '0',
            ],
        ],
    ],
];
